modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "All Rights Reserved"

[[mods]] #mandatory
modId = "myrpg_core" #mandatory
version = "0.1.0" #mandatory
displayName = "Myyyst RPG: Core" #mandatory
authors = "Myyyst" #optional
description = '''The core engine of the Myyyst RPG framework.''' #mandatory

[[dependencies.myrpg_core]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.myrpg_core]]
modId = "minecraft"
type = "required"
versionRange = "[26.2, 26.3)"
ordering = "NONE"
side = "BOTH"