plugins {
    id 'multiloader-common'
}

def loaderAttribute =
        Attribute.of('io.github.mcgradleconventions.loader', String)

// fabric/neoforge -> sibling common project
def commonProjectPath = "${project.parent.path}:common"

configurations {
    commonJava {
        canBeResolved = true
        canBeConsumed = false
    }

    commonResources {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    compileOnly(project(commonProjectPath)) {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }

    commonJava(project(
            path: commonProjectPath,
            configuration: 'commonJava'
    ))

    commonResources(project(
            path: commonProjectPath,
            configuration: 'commonResources'
    ))
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('processResources') {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)

    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}